### PR TITLE
#14 [build-recipe-plugin] Test failure over windows

### LINKED ISSUE #14: [build-recipe-plugin] Test failure over windows
**Describe the bug**
Functional test fails over windows.

**To Reproduce**

**Expected behavior**
Test must passes over all envs.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Seems linefeed difference of windows console.
Need to debug this over windows env.

### PR DESCRIPTION
**Pull request by yuinacor**
Related-issue: #14

### CODE REVIEW

**Review by noveler17 — APPROVED** [review]

File: build-recipe-plugin/src/test/kotlin/com/linecorp/support/project/multi/recipe/FunctionalTest.kt [hunk 1]
```diff
@@ -78,11 +79,11 @@ project ':juice:api:server' is configured by
         GradleRunner.create()
                 .withProjectDir(file.toFile())
                 .withPluginClasspath()
-                .withArguments("allProjectReport", "--stacktrace")
-                .withGradleVersion("5.5.1")
+                .withArguments("allProjectReport")
                 .build()
                 .also { println(it.output) }
-                .also { assertThat(it.output.contains(expected)).isTrue() }
+                .let { it.output.normaliseLineSeparators() }
```
Comment (noveler17) [inline build-recipe-plugin/src/test/kotlin/com/linecorp/support/project/multi/recipe/FunctionalTest.kt:85]: Thank you for your fix! :)

**Review by noveler17 — APPROVED** [review]
